### ISSUE TITLE
Issue With Highlights Panel

### ISSUE THREAD

**Issue by mhousaini** [ChenZaichuang/salesforce_show_api_name#2]
Not sure if there's anything you can do about this, but when you choose to show API names, the look of the highlights panel is degraded, particularly when you scroll down.

![image](https://user-images.githubusercontent.com/33571987/91437839-d93f1e00-e8ad-11ea-8808-5c685caa682c.png)

Before:

![image](https://user-images.githubusercontent.com/33571987/91437877-e4924980-e8ad-11ea-9d0c-bc70078d6504.png)

After: 

![image](https://user-images.githubusercontent.com/33571987/91437896-ea882a80-e8ad-11ea-9270-36e804fa20ba.png)

After scrolling down: 

![image](https://user-images.githubusercontent.com/33571987/91437911-efe57500-e8ad-11ea-84c6-0a4226854a93.png)

**Comment by ChenZaichuang** [comment]
Thanks for your feedback again, I will look into this soon.

**Comment by ChenZaichuang** [comment]
@ze-better Thanks for your feedback again, I will look into this soon.

**Comment by ChenZaichuang** [comment]
@ze-better This issue has been fixed, just reinstall or update the extension.
