### ISSUE TITLE
Keyboard Shortcut Not Working

### ISSUE THREAD

**Issue by mhousaini** [ChenZaichuang/salesforce_show_api_name#3]
Pressing **Ctrl + Shift + Z** doesn't do anything for me. Is this supposed to activate the extension on Windows machines?

I'm running:

- Windows 10
- Chrome Version 84.0.4147.125

**Comment by ChenZaichuang** [comment]
@ze-better Will look into this issue soon, thanks again.

**Comment by ChenZaichuang** [comment]
@ze-better Just come back from my vacation, the keyboard shortcut in windows should be 'alt + shift + z', I have tested it on Windows 10, it works. Welcome for more feedbacks.
